#!/usr/bin/env node

import { Command } from 'commander';
import path from 'path';
import {ls, generateAsciiArt} from './index.js';



const program = new Command();

program
.command('ls <file>')
.description('List file')
.action( async (file) => {
const absolutePath = path.resolve(file);
console.log(await ls(absolutePath));
});

program
.command('ascii <filepath>')
.option('-h, --height <number>', 'height of ascii art', 50)
.option('-w, --width <number>', 'width of ascii art', 50)
.action(async(filepath, options) => {
const absolutePath = path.resolve(filepath);
console.log(await generateAsciiArt(absolutePath));
});


program
.command('rm <file>')
.description('Remove file')
.action((file) => {
const absolutePath = path.resolve(file);
console.log(`Removing file: ${absolutePath}`);
});

program.parse(process.argv);